---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "client/**/*.css"
  - "client/**/*.js"
  - "backend/globaleaks/**/*.py"
